name: covid_19_detector
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_indicator: ^0.4.1
  url_launcher: ^6.0.10
  google_maps_flutter: ^2.0.9
  geolocator: ^8.0.5
  location: ^4.3.0
  material_floating_search_bar: ^0.3.5
  dio: ^4.0.4
  provider: ^6.0.2
  shimmer: ^2.0.0
  flutter_typeahead: ^3.2.4
  timeago: ^2.0.26
  geocoding: ^2.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  great_circle_distance: ^1.0.1
  geocoder: ^0.2.1
  uuid: ^3.0.6
  google_place: ^0.4.7
  flutter_polyline_points: ^1.0.0
  cloud_firestore: ^2.1.0
  http: 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
  adaptive_icon_foreground: "assets/images/adaptive_logo.png"
  adaptive_icon_background: "#ffffff"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Logo2.jpg
    - assets/images/valid.png
    - assets/images/unvalid.png
    - assets/images/symptoms/weakness.jpg
    - assets/images/symptoms/cough.jpg
    - assets/images/symptoms/fatigue.jpg
    - assets/images/symptoms/fever.jpg
    - assets/images/symptoms/stuffy_nose.jpg
    - assets/images/symptoms/shortness_of_breath.jpg
    - assets/images/preventions/disinfect_surfaces.jpg
    - assets/images/preventions/excercise_and_eat_healthy.jpg
    - assets/images/preventions/maintain_a_safe_distance.jpg
    - assets/images/preventions/stay_home.jpg
    - assets/images/preventions/wash_your_hands.jpg
    - assets/images/preventions/wear_a_mask.jpg
    - assets/images/virus.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
