class Wrong {
  static List<String> wrongCountries = [
    'Saint Helena',
    'Saint Pierre and Miquelon',
    'Gibraltar',
    'Svalbard and Jan Mayen Islands',
    'Cocos (Keeling) Islands',
    'British Virgin Islands',
    'Northern Mariana Islands',
    'Pitcairn',
    'Netherlands Antilles',
    'Norfolk Island',
    'Hong Kong, SAR China',
    'Bermuda',
    'French Southern Territories',
    'Guam',
    'Turkmenistan',
    'Aruba',
    'Isle of Man',
    'US Minor Outlying Islands',
    'New Caledonia',
    'South Georgia and the South Sandwich Islands',
    'Western Sahara',
    'American Samoa',
    'Guernsey',
    'Martinique',
    'Jersey',
    'Cayman Islands',
    'Saint-Martin (French part)',
    'Wallis and Futuna Islands',
    'Falkland Islands (Malvinas)',
    'Cook Islands',
    'Macao, SAR China',
    'Turks and Caicos Islands',
    'Mayotte',
    'Montserrat',
    'Nauru',
    'Anguilla',
    'Tuvalu',
    'Faroe Islands',
    'Niue',
    'Guadeloupe',
    'ALA Aland Islands',
    'French Polynesia',
    'British Indian Ocean Territory',
    'Christmas Island',
    'Puerto Rico',
    'Tokelau',
    'Bouvet Island',
    'French Guiana',
    'Heard and Mcdonald Islands',
    'Virgin Islands, US',
    'Greenland'
  ];
}
